services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: treadmill-app
    command: bash -c "mkdir -p /var/www/html/uploads/debug /var/www/html/uploads/history && chmod -R 0777 /var/www/html/uploads /var/www/.EasyOCR && apache2-foreground"
    ports:
      - "4001:80"
    volumes:
      - app_uploads:/var/www/html/uploads
      - easyocr_cache:/var/www/.EasyOCR
    environment:
      DB_HOST: db
      DB_USER: treadmill_user
      DB_PASS: treadmill_pass
      DB_NAME: treadmill_db
    networks:
      - treadmill_net
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

  db:
    image: mysql:8.0
    container_name: treadmill-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: treadmill_db
      MYSQL_USER: treadmill_user
      MYSQL_PASSWORD: treadmill_pass
    networks:
      - treadmill_net
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test:
        [
          "CMD",
          "sh",
          "-c",
          "mysqladmin ping -h localhost -uroot -p$$MYSQL_ROOT_PASSWORD",
        ]
      interval: 5s
      timeout: 5s
      retries: 20
    restart: unless-stopped

  # phpmyadmin:
  # image: phpmyadmin:latest
  # container_name: treadmill-phpmyadmin
  # ports:
  #   - "8081:80"
  # environment:
  #   PMA_HOST: db
  #   PMA_PORT: 3306
  #   PMA_USER: root
  #   PMA_PASSWORD: root
  # networks:
  #   - treadmill_net
  # depends_on:
  #   db:
  #     condition: service_healthy
  # restart: unless-stopped

volumes:
  db_data:
  app_uploads:
  easyocr_cache:

networks:
  treadmill_net:
    driver: bridge
